// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IDNSSECClient ...
type IDNSSECClient interface {
	// ListKeys returns all DNSSEC keys of the zone with the given ID.
	ListKeys(ctx context.Context, zoneID int) ([]*DNSSECKey, *Response, error)
	// GetKey returns a single DNSSEC key of the zone.
	GetKey(ctx context.Context, zoneID, keyID int) (*DNSSECKey, *Response, error)
	// AddKey creates a new DNSSEC key for the zone and returns it.
	//
	// PowerDNS creates keys inactive; use [DNSSECClient.SetKeyActive] to activate
	// the new key.
	AddKey(ctx context.Context, zoneID int, opts DNSSECKeyCreateOpts) (*DNSSECKey, *Response, error)
	// SetKeyActive activates or deactivates a DNSSEC key and returns its new state.
	// Setting the state the key already has is not an error.
	SetKeyActive(ctx context.Context, zoneID, keyID int, active bool) (*DNSSECKey, *Response, error)
	// DeleteKey deletes a DNSSEC key of the zone.
	DeleteKey(ctx context.Context, zoneID, keyID int) (*Response, error)
	// Rectify recalculates the DNSSEC ordering and auth fields of a signed zone.
	// The server answers 409 for unsigned, presigned and secondary zones.
	Rectify(ctx context.Context, zoneID int) (*Response, error)
}
