// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IGroupClient ...
type IGroupClient interface {
	// GetByName returns a single [Group] by name.
	// Paginates the list endpoint and matches client-side.
	GetByName(ctx context.Context, name string) (*Group, *Response, error)
	// GetByID returns a single [Group] by ID.
	GetByID(ctx context.Context, id int) (*Group, *Response, error)
	// List returns one page of [Group]s.
	List(ctx context.Context, opts ListOpts) ([]*Group, *Response, error)
	// All returns all [Group]s across all pages.
	All(ctx context.Context) ([]*Group, error)
	// Create creates a new [Group] and returns the new ID.
	Create(ctx context.Context, opts GroupCreateOpts) (int, *Response, error)
	// Update updates an existing [Group] and returns the updated state.
	Update(ctx context.Context, id int, opts GroupUpdateOpts) (*Group, *Response, error)
	// Delete deletes the [Group] with the given ID.
	Delete(ctx context.Context, id int) (*Response, error)
	// Members returns the [GroupMember]s of a group.
	Members(ctx context.Context, id int) ([]*GroupMember, *Response, error)
	// AddMember adds a user to a group.
	AddMember(ctx context.Context, groupID, userID int) (*Response, error)
	// RemoveMember removes a user from a group.
	RemoveMember(ctx context.Context, groupID, userID int) (*Response, error)
	// Zones returns the zones associated with a group.
	Zones(ctx context.Context, id int) ([]*GroupZone, *Response, error)
	// AddZone associates a zone with a group.
	AddZone(ctx context.Context, groupID, zoneID int) (*Response, error)
	// RemoveZone disassociates a zone from a group.
	RemoveZone(ctx context.Context, groupID, zoneID int) (*Response, error)
}
