// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IPermissionClient ...
type IPermissionClient interface {
	// GetByID returns a single [Permission] by ID.
	GetByID(ctx context.Context, id int) (*Permission, *Response, error)
	// List returns one page of [Permission]s.
	List(ctx context.Context, opts ListOpts) ([]*Permission, *Response, error)
	// All returns all [Permission]s across all pages.
	All(ctx context.Context) ([]*Permission, error)
}
