// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IPermissionTemplateClient ...
type IPermissionTemplateClient interface {
	// GetByName returns a single [PermissionTemplate] by name.
	// Falls back to a list scan since there is no dedicated by-name endpoint.
	// Note: list responses do not include the full permission list — call
	// [PermissionTemplateClient.GetByID] on the result to get permissions.
	GetByName(ctx context.Context, name string) (*PermissionTemplate, *Response, error)
	// GetByID returns a single [PermissionTemplate] with its full permission list.
	GetByID(ctx context.Context, id int) (*PermissionTemplate, *Response, error)
	// List returns all [PermissionTemplate]s. The permission list is typically not
	// populated in list responses — use [PermissionTemplateClient.GetByID] for that.
	List(ctx context.Context) ([]*PermissionTemplate, *Response, error)
	// Create creates a new [PermissionTemplate].
	Create(ctx context.Context, opts PermissionTemplateOpts) (*PermissionTemplate, *Response, error)
	// Update updates an existing [PermissionTemplate].
	Update(ctx context.Context, id int, opts PermissionTemplateOpts) (*PermissionTemplate, *Response, error)
	// Delete deletes a [PermissionTemplate].
	Delete(ctx context.Context, id int) (*Response, error)
}
