// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IRRSetClient ...
type IRRSetClient interface {
	// Get returns a single [RRSet] identified by name and type within a zone.
	Get(ctx context.Context, zoneID int, name, recordType string) (*RRSet, *Response, error)
	// List returns all [RRSet]s in a zone.
	List(ctx context.Context, zoneID int) ([]*RRSet, *Response, error)
	// Upsert creates or replaces an [RRSet] via PUT. The API treats this as an
	// idempotent create-or-update on (name, type) within the zone.
	Upsert(ctx context.Context, zoneID int, opts RRSetUpsertOpts) (*Response, error)
	// Delete deletes the [RRSet] identified by name and type within a zone.
	Delete(ctx context.Context, zoneID int, name, recordType string) (*Response, error)
}
