// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IZoneTemplateClient ...
type IZoneTemplateClient interface {
	// GetByName returns a single [ZoneTemplate] by name.
	// The template endpoint is not paginated, so this is a single-page scan.
	GetByName(ctx context.Context, name string) (*ZoneTemplate, *Response, error)
	// GetByID returns a single [ZoneTemplate].
	GetByID(ctx context.Context, id int) (*ZoneTemplate, *Response, error)
	// List returns all [ZoneTemplate]s.
	List(ctx context.Context) ([]*ZoneTemplate, *Response, error)
	// Create creates a new [ZoneTemplate].
	Create(ctx context.Context, opts ZoneTemplateCreateOpts) (*ZoneTemplate, *Response, error)
	// Update updates an existing [ZoneTemplate].
	//
	// The update endpoint returns no data, so Update reads the template back with
	// an additional GET to return the persisted state.
	Update(ctx context.Context, id int, opts ZoneTemplateUpdateOpts) (*ZoneTemplate, *Response, error)
	// Delete deletes a [ZoneTemplate].
	Delete(ctx context.Context, id int) (*Response, error)
	// Records returns all records belonging to the template.
	Records(ctx context.Context, templateID int) ([]*ZoneTemplateRecord, *Response, error)
	// GetRecord returns a single template record.
	GetRecord(ctx context.Context, templateID, recordID int) (*ZoneTemplateRecord, *Response, error)
	// CreateRecord adds a record to a template.
	CreateRecord(ctx context.Context, templateID int, opts ZoneTemplateRecordOpts) (*ZoneTemplateRecord, *Response, error)
	// UpdateRecord replaces a template record.
	//
	// The update endpoint returns no data, so UpdateRecord reads the record back
	// with an additional GET to return the persisted state.
	UpdateRecord(ctx context.Context, templateID, recordID int, opts ZoneTemplateRecordOpts) (*ZoneTemplateRecord, *Response, error)
	// DeleteRecord removes a record from a template.
	DeleteRecord(ctx context.Context, templateID, recordID int) (*Response, error)
}
