// Code generated by ifacemaker; DO NOT EDIT.

package poweradmin

import (
	"context"
)

// IZoneClient ...
type IZoneClient interface {
	// GetByID returns a single [Zone] by its numeric ID.
	GetByID(ctx context.Context, id int) (*Zone, *Response, error)
	// GetByName returns a single [Zone] by its DNS name.
	// Performs a list + linear search across all pages — no dedicated API endpoint exists.
	GetByName(ctx context.Context, name string) (*Zone, *Response, error)
	// List returns one page of [Zone]s. The list endpoint only returns ID, Name,
	// Type and CreatedAt; see [Zone].
	List(ctx context.Context, opts ListOpts) ([]*Zone, *Response, error)
	// All returns all [Zone]s across all pages.
	All(ctx context.Context) ([]*Zone, error)
	// Create creates a new [Zone] and returns the new ID.
	// Call [ZoneClient.GetByID] to fetch the full object.
	Create(ctx context.Context, opts ZoneCreateOpts) (int, *Response, error)
	// Update updates an existing [Zone] and returns the updated state.
	Update(ctx context.Context, id int, opts ZoneUpdateOpts) (*Zone, *Response, error)
	// Delete deletes the [Zone] with the given ID.
	Delete(ctx context.Context, id int) (*Response, error)
	// Owners returns all owners of the zone.
	Owners(ctx context.Context, zoneID int) ([]*ZoneOwner, *Response, error)
	// AddOwner adds a single user as owner of the zone.
	AddOwner(ctx context.Context, zoneID, userID int) (*Response, error)
	// AddOwners adds multiple users as owners in a single request.
	AddOwners(ctx context.Context, zoneID int, userIDs []int) (*Response, error)
	// RemoveOwner removes a user from the zone's owners.
	RemoveOwner(ctx context.Context, zoneID, userID int) (*Response, error)
	// GetDNSSEC returns the DNSSEC status of the zone with the given ID.
	GetDNSSEC(ctx context.Context, id int) (*ZoneDNSSEC, *Response, error)
	// SetDNSSEC enables or disables DNSSEC for the zone with the given ID.
	SetDNSSEC(ctx context.Context, id int, enabled bool) (*ZoneDNSSEC, *Response, error)
	// ListMetadata returns all metadata entries for the zone with the given ID.
	ListMetadata(ctx context.Context, zoneID int) ([]*ZoneMetadata, *Response, error)
	// GetMetadata returns the values stored under a specific metadata kind
	// (e.g. ALLOW-AXFR-FROM) for the zone with the given ID.
	GetMetadata(ctx context.Context, zoneID int, kind string) (*ZoneMetadata, *Response, error)
	// SetMetadata creates or replaces all values for a metadata kind on the zone
	// with the given ID.
	SetMetadata(ctx context.Context, zoneID int, kind string, values []string) (*Response, error)
	// DeleteMetadata deletes all values for a metadata kind on the zone with the
	// given ID.
	DeleteMetadata(ctx context.Context, zoneID int, kind string) (*Response, error)
}
